<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Colors/Color.fs" />
    <Compile Include="Colors/Stroke.fs" />

    <Compile Include="Utils/Math.fs" />
    <Compile Include="Utils/Image.fs" />

    <Compile Include="Render/Projector.fs" />
    <Compile Include="Render/Buffer.fs" />
    <Compile Include="Render/Display.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
